SEARCH_WORDS = [
    "seventeen",
    "seventeen 克拉",
    "seventeen 賽文婷",
    "seventeen 演唱會",
    "seventeen 門票",
    "seventeen 票",
    "seventeen 讓票",
    "seventeen 讓售",
    "seventeen 售票",
    "seventeen 小卡",
    "seventeen 專輯",
    "seventeen 周邊",
    "seventeen 手燈",
    "seventeen 應援棒",
    "seventeen 卡冊",
    "seventeen 拍立得",
    "seventeen 交換",
    "seventeen 收卡",
    "seventeen 出卡",
    "seventeen 代購",
    "seventeen 克拉盤",
    "seventeen 特典",
    "seventeen 未拆",
    "seventeen 現貨",
    "seventeen 拆售",
    "seventeen 分售",
    "seventeen 官周",
    "seventeen 娃娃",
    "seventeen 立牌",
    "seventeen 明信片",
    "seventeen 幸運抽",
    "seventeen 預購",
    "seventeen 簽售",
    "seventeen 粉絲見面會",
    "seventeen 克拉島",
    "seventeen 台北",
    "seventeen 高雄",
    "seventeen 香港",
    "seventeen 澳門",
    "seventeen 首爾",
    "seventeen 仁川",
    "seventeen 日本",
    "seventeen 東京",
    "seventeen 大阪",
    "seventeen 名古屋",
    "seventeen 福岡",
    "seventeen 崔勝哲",
    "seventeen 淨漢",
    "seventeen 尹淨漢",
    "seventeen 尹净汉",
    "seventeen 約書亞",
    "seventeen 洪知秀",
    "seventeen 俊",
    "seventeen 文俊輝",
    "seventeen 文俊辉",
    "seventeen 權順榮",
    "seventeen 权顺荣",
    "seventeen 圓佑",
    "seventeen 全圓佑",
    "seventeen 全圆佑",
    "seventeen 李知勳",
    "seventeen 李知勋",
    "seventeen 徐明浩",
    "seventeen 珉奎",
    "seventeen 金珉奎",
    "seventeen 李碩珉",
    "seventeen 李硕珉",
    "seventeen 勝寬",
    "seventeen 夫勝寬",
    "seventeen 夫胜宽",
    "seventeen 韓率",
    "seventeen 李燦",
    "seventeen 李灿",
]

SEARCH_WORD = SEARCH_WORDS[0]
MAX_N = 100000
MAX_IDLE_ROUNDS = 24

telegram_bot_token = "8918481952:AAEokqzGoKK456vCMZ5DSRmrKiRcLXcDCjI"
telegram_chat_id = "6531737395"
