SEARCH_WORDS = [
    "seventeen",
    "svt",
    "세븐틴",
    "セブチ",
    "セブンティーン",
    "carat",
    "캐럿",
    "克拉",
    "seventeen 演唱會",
    "seventeen 콘서트",
    "seventeen concert",
    "svt 演唱會",
    "svt 콘서트",
    "세븐틴 콘서트",
    "세븐틴 공연",
    "seventeen 門票",
    "seventeen 票",
    "seventeen 티켓",
    "세븐틴 티켓",
    "세븐틴 양도",
    "세븐틴 티켓팅",
    "seventeen 讓票",
    "seventeen 讓售",
    "seventeen 售票",
    "seventeen photocard",
    "seventeen album",
    "seventeen merch",
    "seventeen poca",
    "seventeen trading card",
    "seventeen 小卡",
    "seventeen 專輯",
    "seventeen 周邊",
    "seventeen 手燈",
    "seventeen 應援棒",
    "seventeen 卡冊",
    "seventeen 拍立得",
    "seventeen 交換",
    "seventeen 收卡",
    "seventeen 出卡",
    "seventeen 代購",
    "小卡 seventeen",
    "專輯 seventeen",
    "周邊 seventeen",
    "手燈 seventeen",
    "應援棒 seventeen",
    "svt photocard",
    "svt album",
    "svt merch",
    "svt poca",
    "svt trading card",
    "svt 小卡",
    "svt 專輯",
    "svt 周邊",
    "svt 手燈",
    "svt 應援棒",
    "svt 交換",
    "svt 收卡",
    "svt 出卡",
    "svt 代購",
    "세븐틴 포카",
    "세븐틴 포토카드",
    "세븐틴 앨범",
    "세븐틴 굿즈",
    "세븐틴 응원봉",
    "세븐틴 캐럿봉",
    "세븐틴 교환",
    "세븐틴 양도",
    "세븐틴 판매",
    "세븐틴 대리구매",
    "세븐틴 미개봉",
    "세븐틴 럭드",
    "세븐틴 특전",
    "세븐틴 포카 교환",
    "세븐틴 포카 양도",
    "세븐틴 앨범 양도",
    "세븐틴 굿즈 양도",
    "セブチ トレカ",
    "セブチ アルバム",
    "セブチ グッズ",
    "セブチ ライブ",
    "セブチ チケット",
    "エスクプス",
    "淨漢",
    "정한",
    "jeonghan",
    "尹淨漢",
    "尹净汉",
    "約書亞",
    "조슈아",
    "joshua",
    "俊",
    "文俊輝",
    "文俊辉",
    "준",
    "jun",
    "Hoshi",
    "호시",
    "權順榮",
    "权顺荣",
    "Wonwoo",
    "원우",
    "全圓佑",
    "全圆佑",
    "Woozi",
    "우지",
    "李知勳",
    "李知勋",
    "The8",
    "디에잇",
    "徐明浩",
    "Mingyu",
    "민규",
    "金珉奎",
    "DK",
    "도겸",
    "李碩珉",
    "李硕珉",
    "Seungkwan",
    "승관",
    "夫勝寬",
    "夫胜宽",
    "Vernon",
    "버논",
    "Dino",
    "디노",
    "李燦",
    "李灿",
    "s.coups photocard",
    "scoups photocard",
    "jeonghan photocard",
    "joshua photocard",
    "jun photocard",
    "hoshi photocard",
    "wonwoo photocard",
    "woozi photocard",
    "the8 photocard",
    "minghao photocard",
    "mingyu photocard",
    "dk photocard",
    "seokmin photocard",
    "seungkwan photocard",
    "vernon photocard",
    "dino photocard",
    "淨漢 小卡",
    "淨漢 交換",
    "淨漢 讓售",
    "정한 포카",
    "정한 교환",
    "정한 양도",
    "珉奎 小卡",
    "珉奎 交換",
    "珉奎 讓售",
    "민규 포카",
    "민규 교환",
    "민규 양도",
    "圓佑 小卡",
    "圓佑 交換",
    "圓佑 讓售",
    "원우 포카",
    "원우 교환",
    "원우 양도",
    "seventeen 2026",
    "seventeen 2025",
    "seventeen 2024",
    "seventeen january",
    "seventeen february",
    "seventeen march",
    "seventeen april",
    "seventeen may",
    "seventeen june",
    "seventeen july",
    "seventeen august",
    "seventeen september",
    "seventeen october",
    "seventeen november",
    "seventeen december",
    "svt 2026",
    "svt 2025",
    "svt 2024",
    "세븐틴 2026",
    "세븐틴 2025",
    "세븐틴 2024",
    "seventeen 台北",
    "seventeen 高雄",
    "seventeen 香港",
    "seventeen 澳門",
    "seventeen 首爾",
    "seventeen 仁川",
    "seventeen 日本",
    "seventeen 東京",
    "seventeen 大阪",
    "seventeen 名古屋",
    "seventeen 福岡",
    "svt 台北",
    "svt 高雄",
    "svt 香港",
    "svt 首爾",
    "svt 東京",
    "세븐틴 서울",
    "세븐틴 인천",
    "세븐틴 일본",
    "세븐틴 도쿄",
    "세븐틴 오사카",
    "seventeen resale",
    "seventeen sell",
    "seventeen wts",
    "seventeen wtb",
    "seventeen trade",
    "svt resale",
    "svt sell",
    "svt wts",
    "svt wtb",
    "svt trade",
    "seventeen lucky draw",
    "seventeen ld",
    "seventeen pobs",
    "seventeen pob",
    "svt lucky draw",
    "svt pob",
    "svt pobs",
    "세븐틴 럭키드로우",
    "세븐틴 미공포",
    "세븐틴 사웨",
    "세븐틴 위버스",
    "세븐틴 위드뮤",
    "세븐틴 예판",
    "세븐틴 팬싸",
    "세븐틴 팬미팅",
    "세븐틴 캐럿랜드",
    "세븐틴 팔로우",
    "세븐틴 비더썬",
    "세븐틴 오드투유",
    "세븐틴 헹가래",
    "seventeen caratland",
    "seventeen follow",
    "seventeen be the sun",
    "seventeen ode to you",
    "seventeen henggarae",
    "seventeen fml",
    "seventeen seventeenth heaven",
    "seventeen spill the feels",
    "svt caratland",
    "svt follow",
    "svt be the sun",
    "svt fml",
    "svt seventeenth heaven",
    "svt spill the feels",
    "seventeen 克拉盤",
    "seventeen 特典",
    "seventeen 未拆",
    "seventeen 現貨",
    "seventeen 拆售",
    "seventeen 分售",
    "seventeen 官周",
    "seventeen 娃娃",
    "seventeen 立牌",
    "seventeen 明信片",
    "seventeen postcard",
    "seventeen binder",
    "seventeen lightstick",
    "svt 特典",
    "svt 未拆",
    "svt 現貨",
    "svt 拆售",
    "svt 分售",
    "svt 官周",
    "svt 娃娃",
    "svt 立牌",
    "svt 明信片",
    "svt postcard",
    "svt binder",
    "svt lightstick",
    "崔勝哲 小卡",
    "崔勝哲 交換",
    "崔勝哲 讓售",
    "에스쿱스 포카",
    "에스쿱스 교환",
    "에스쿱스 양도",
    "洪知秀 小卡",
    "洪知秀 交換",
    "洪知秀 讓售",
    "조슈아 포카",
    "조슈아 교환",
    "조슈아 양도",
    "文俊輝 小卡",
    "文俊輝 交換",
    "文俊輝 讓售",
    "준 포카",
    "준 교환",
    "준 양도",
    "權順榮 小卡",
    "權順榮 交換",
    "權順榮 讓售",
    "호시 포카",
    "호시 교환",
    "호시 양도",
    "李知勳 小卡",
    "李知勳 交換",
    "李知勳 讓售",
    "우지 포카",
    "우지 교환",
    "우지 양도",
    "徐明浩 小卡",
    "徐明浩 交換",
    "徐明浩 讓售",
    "디에잇 포카",
    "디에잇 교환",
    "디에잇 양도",
    "李碩珉 小卡",
    "李碩珉 交換",
    "李碩珉 讓售",
    "도겸 포카",
    "도겸 교환",
    "도겸 양도",
    "夫勝寬 小卡",
    "夫勝寬 交換",
    "夫勝寬 讓售",
    "승관 포카",
    "승관 교환",
    "승관 양도",
    "韓率 小卡",
    "韓率 交換",
    "韓率 讓售",
    "버논 포카",
    "버논 교환",
    "버논 양도",
    "李燦 小卡",
    "李燦 交換",
    "李燦 讓售",
    "디노 포카",
    "디노 교환",
    "디노 양도",
]
SEARCH_WORD = SEARCH_WORDS[0]
MAX_N = 50000
MAX_IDLE_ROUNDS = 24

telegram_bot_token = "8918481952:AAEokqzGoKK456vCMZ5DSRmrKiRcLXcDCjI"
telegram_chat_id = "6531737395"